### ISSUE TITLE
Implementation with Paul Irish' infiniteScroll?

### ISSUE THREAD

**Issue by Twansparant** [jeffstephens/infinitescroll#1]
Hi there,

Your solution looks promising!
I'm just wundering how I could implement this within an existing infiniteScroll (with Isotope also) setup like this:

``` javascript
// InfiniteScroll
$container.infinitescroll({
  loading: {
    msgText:        'loading',
    finishedMsg:    'finished',
    img:            "/assets/img/loading-icon.gif",
    speed:          'fast'
  },
  nextSelector:     ".post-nav li.next a",
  navSelector:      ".post-nav",
  itemSelector:     ".grid .hentry",
  },
  // Isotope callback
  function(newElements) {
    $container.isotope('appended', $(newElements));
  }
);
```

Where the next load of posts is a Wordpress archive page.
I see you don't use Paul Irish' infiniteScroll at all, but instead you fetch new posts with this function:

``` javascript
function fetchPosts(){
    $('#loading').fadeIn();
    $.get( 'backend.php', { 'oldestPost' : oldestPost, 'fetchUntil' : fetchUntil }, function(JSON){
        data = $.parseJSON(JSON);
        oldestPost = data.oldestPost;
        window.location.hash = oldestPost;
        $('#feed').append(data.html);
        $('#loading').fadeOut();
        fetchUntil = ''; // only used at first request
        // scroll to bottom-most element
        $("html, body").animate({ scrollTop: $('#' + oldestPost).offset().top}, 1000);
    });
}
```

Is there an easy way to use both techniques?
Thanks!

**Comment by jackyon** [comment]
+1

**Comment by jeffstephens** [comment]
Hi, I'm not familiar with Paul Irish's infiniteScroll, but the technique I use shouldn't be too hard to adapt. I'd imagine you just need to add a hash code to the existing AJAX calls... so the server should return `md5($lastPost['title'])` or something, then have the Javascript side add that to `window.location.hash`. When the page loads for the first time, check for that `window.location.hash` and if it's present, send it with your initial AJAX request so the server can keep returning posts until it finds one such that `$row['title'] = $_POST['hash']`, for example.
